In [23]:
import pandas as pd
import numpy as np
import pickle

pd.set_option('display.max_columns', None)
pd.set_option("display.max_colwidth",1000)

# This notebook shows the scripts and analysis at the same time for association rules of min support of 0.3 and confidence of 0.8

In [ ]:
df=pickle.load(open("association_rules_minsup30_confi_80.p","rb"))

created a dataframe containing each association rule as a and its sup  and confidence and right and left side attributes

In [2]:
file=open("results/decoded_association_rules_minsup30_confi_80.txt")

In [3]:
l=["left" for i in range(25)]
l.extend(["right" for i in range(25)])
l.extend(["sup","conf","rule"])
df=pd.DataFrame(columns=[l,["AGER20", "ANARR","DEROU" ,"DIPL_15", "EMPL", "ETUD", "GARL", "ILTUU", "IMMI", "INAT", "INFAM", "INPER", "MODV",
"NATC", "NBPI", "NPERR", "RECH", "SFM", "TACT", "VOIT","TYPMR","TRANS","PNAI12", "CS2","TYPL","AGER20", "ANARR","DEROU" ,"DIPL_15", "EMPL", "ETUD", "GARL", "ILTUU", "IMMI", "INAT", "INFAM", "INPER", "MODV",
"NATC", "NBPI", "NPERR", "RECH", "SFM", "TACT", "VOIT","TYPMR","TRANS","PNAI12", "CS2","TYPL","sup","conf","rule"]])
for line in file:
    l=line.split("#")
    asoc=l[0].split("==>")
    asoc_from=asoc[0].strip().replace(", '",",'").split(" ")
    asoc_to=asoc[1].strip().replace(", '",",'").split(" ")
    dic={}
    dic[("sup","sup")]=float(l[1][5:])
    dic[("conf","conf")]=float(l[2][6:len(l[2])-2])
    dic[("rule","rule")]=l[0]

    for i in asoc_from:
        tup=i.split("','")
        col=tup[0][2:]
        val=tup[1][:len(tup[1])-2]
        dic[("left",col)]=val
    for i in asoc_to:
        tup=i.split("','")
        col=tup[0][2:]
        val=tup[1][:len(tup[1])-2]
        dic[("right",col)]=val
    df=df.append(dic,ignore_index=True)

In [4]:
df.shape

(86038, 53)

i removed all the coloumns which have all its values as nan

In [166]:
df=df.loc[:,np.logical_not(df.isna()).sum()!=0]
df.head()

left                                                                       \
  ANARR DEROU EMPL ETUD GARL ILTUU IMMI INAT INFAM NATC RECH TACT VOIT TYPMR   
0   NaN     Z  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   NaN   
1     Z   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   NaN   
2   NaN   NaN   ZZ  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   NaN   
3   NaN   NaN  NaN  2.0  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   NaN   
4   NaN   NaN  NaN  NaN  1.0   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   NaN   

                         right                                             \
  TRANS PNAI12  CS2 TYPL ANARR DEROU EMPL ETUD GARL ILTUU IMMI INAT INFAM   
0   NaN    NaN  NaN  NaN     Z   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN   
1   NaN    NaN  NaN  NaN   NaN     Z  NaN  NaN  NaN   NaN  NaN  NaN   NaN   
2   NaN    NaN  NaN  NaN     Z   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN   
3   NaN    NaN  NaN  NaN     Z   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN   
4   NaN    NaN  NaN  NaN     Z   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN   

                                     sup      conf  \
  NATC RECH TACT TRANS PNAI12        sup      conf   
0  NaN  NaN  NaN   NaN    NaN  1070144.0  0.878290   
1  NaN  NaN  NaN   NaN    NaN  1070144.0  0.999999   
2  NaN  NaN  NaN   NaN    NaN   636248.0  0.873151   
3  NaN  NaN  NaN   NaN    NaN   806444.0  0.865434   
4  NaN  NaN  NaN   NaN    NaN   751396.0  0.903980   

                                  rule right_length left_length  
                                  rule                           
0   ('DEROU', 'Z') ==> ('ANARR', 'Z')             1           1  
1   ('ANARR', 'Z') ==> ('DEROU', 'Z')             1           1  
2   ('EMPL', 'ZZ') ==> ('ANARR', 'Z')             1           1  
3  ('ETUD', '2.0') ==> ('ANARR', 'Z')             1           1  
4  ('GARL', '1.0') ==> ('ANARR', 'Z')             1           1

In [24]:
# pickle.dump( df, open( "association_rules_minsup30_confi_80.p", "wb" ) )

Counting the length of the attributes for the left and the right respectively to ease the axess to the results and analysis

In [44]:
df['left_length'] = df.loc[:,"left"].apply(lambda x: x.count(), axis=1)

In [45]:
df['right_length'] = df.loc[:,"right"].apply(lambda x: x.count(), axis=1)

I am interested to study the status of the immigrants in GrandEst so I searched for the rules which contain the IMMI attribute with value to 1 which indicates the immigration.

In [11]:
df[df.loc[:,('left','IMMI')]=='1.0']

Empty DataFrame
Columns: [(left, ANARR), (left, DEROU), (left, EMPL), (left, ETUD), (left, GARL), (left, ILTUU), (left, IMMI), (left, INAT), (left, INFAM), (left, NATC), (left, RECH), (left, TACT), (left, VOIT), (left, TYPMR), (left, TRANS), (left, PNAI12), (left, CS2), (left, TYPL), (right, ANARR), (right, DEROU), (right, EMPL), (right, ETUD), (right, GARL), (right, ILTUU), (right, IMMI), (right, INAT), (right, INFAM), (right, NATC), (right, RECH), (right, TACT), (right, TRANS), (right, PNAI12), (sup, sup), (conf, conf), (rule, rule)]
Index: []

But it seems that there is no confident rules for immi=1

 checking the unique values before deciding what to analyse because!!! the values in the dataset are not good at all and every time i have a senario in mind i cannot find the right attributes and values that justify it so i found this way is better 

In [16]:
df.loc[:,('right','ETUD')].unique()

array([nan, '2.0'], dtype=object)

In [10]:
df.loc[:,('left','VOIT')].unique()

array([nan, '1.0', '2.0'], dtype=object)

In [12]:
df.loc[:,('right','GARL')].unique()

array([nan, '1.0'], dtype=object)

In [99]:
df.loc[:,('left','TRANS')].unique()

array([nan, 'Z', '4'], dtype=object)

In [17]:
df.loc[:,('right','INFAM')].unique()

array([nan, '1.0'], dtype=object)

In [18]:
df.loc[:,('right','PNAI12')].unique()

array([nan, '1.0'], dtype=object)

In [128]:
df.loc[:,('left','TYPMR')].unique() #for example here there is no rule that contain this attribute 
#on the right side so i am forced to anlyse it with it being on the left side

array([nan, '41.0'], dtype=object)

interested to find characteristics of the people in GrandEst who are born in France métropolitaine et DOM-TOM-COM.


Selecting the association rules which have only the attribute PNAI12 in the right side of the rule at the same time have the maximum number of attributes to the left side of the rule and also having confidence of 100%, in this way i am able to collect the maximum number of characteristics of the people in GrandEst who are born in France métropolitaine et DOM-TOM-COM .
As you can see there are alot in common between the rules.


In [88]:
df_rule1=df[np.logical_and(np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,
                                                np.logical_not(df.loc[:,('right','PNAI12')].isnull()))
                                 ,df.right_length==1),df["left_length"]==df["left_length"].max())].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule1


sup conf  \
            sup conf   
84705  383075.0  1.0   
85152  421895.0  1.0   
85599  484390.0  1.0   

                                                                                                                                                                      rule  
                                                                                                                                                                      rule  
84705   ('ANARR', 'Z') ('DEROU', 'Z') ('EMPL', 'ZZ') ('ETUD', '2.0') ('ILTUU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('NATC', '0.0') ('TRANS', 'Z') ==> ('PNAI12', '1.0')   
85152   ('ANARR', 'Z') ('DEROU', 'Z') ('EMPL', 'ZZ') ('GARL', '1.0') ('ILTUU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('NATC', '0.0') ('TRANS', 'Z') ==> ('PNAI12', '1.0')   
85599  ('ANARR', 'Z') ('DEROU', 'Z') ('EMPL', 'ZZ') ('ILTUU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('INFAM', '1.0') ('NATC', '0.0') ('TRANS', 'Z') ==> ('PNAI12', '1.0')

since there are 3 different rules its best to select the one with highest support

('ANARR', 'Z') ('DEROU', 'Z') ('EMPL', 'ZZ') ('ILTUU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('INFAM', '1.0') ('NATC', '0.0') ('TRANS', 'Z') ==> ('PNAI12', '1.0')


we get not very useful information from this, its just that people who are french by birth and not immigrants are born in Frane metroplotaine, which is something logical.And also with INFAM=1 states that there is one family in the household of those people.
but taking the first one with less support indicates that those who are not registered in an educational insitute are born in France metropolitaine.

 Also i am interested to find the characteristics of the people who uses the car i.e TRANS=4 as a Main mode of transport most often used for going to work 

In [126]:

df_rule2=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,df.loc[:,('left','TRANS')]=='4'),df.left_length==1)]
df_rule2

left                                                                 \
     ANARR DEROU EMPL ETUD GARL ILTUU IMMI INAT INFAM NATC RECH TACT VOIT   
43     NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   
128    NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   
130    NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   
698    NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   
705    NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   
1264   NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   
4306   NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN   

                                  right                                       \
     TYPMR TRANS PNAI12  CS2 TYPL ANARR DEROU EMPL ETUD GARL ILTUU IMMI INAT   
43     NaN     4    NaN  NaN  NaN   NaN     Z  NaN  NaN  NaN   NaN  NaN  NaN   
128    NaN     4    NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   
130    NaN     4    NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   
698    NaN     4    NaN  NaN  NaN   NaN     Z  NaN  NaN  NaN   NaN  NaN  NaN   
705    NaN     4    NaN  NaN  NaN   NaN     Z  NaN  NaN  NaN   NaN  NaN  NaN   
1264   NaN     4    NaN  NaN  NaN   NaN   NaN  NaN  NaN  NaN   NaN  NaN  NaN   
4306   NaN     4    NaN  NaN  NaN   NaN     Z  NaN  NaN  NaN   NaN  NaN  NaN   

                                              sup conf  \
     INFAM NATC RECH  TACT TRANS PNAI12       sup conf   
43     NaN  NaN  NaN   NaN   NaN    NaN  370098.0  1.0   
128    NaN  NaN    Z   NaN   NaN    NaN  370098.0  1.0   
130    NaN  NaN  NaN  11.0   NaN    NaN  370098.0  1.0   
698    NaN  NaN    Z   NaN   NaN    NaN  370098.0  1.0   
705    NaN  NaN  NaN  11.0   NaN    NaN  370098.0  1.0   
1264   NaN  NaN    Z  11.0   NaN    NaN  370098.0  1.0   
4306   NaN  NaN    Z  11.0   NaN    NaN  370098.0  1.0   

                                                                   rule  \
                                                                   rule   
43                                   ('TRANS', '4') ==> ('DEROU', 'Z')    
128                                   ('TRANS', '4') ==> ('RECH', 'Z')    
130                                ('TRANS', '4') ==> ('TACT', '11.0')    
698                    ('TRANS', '4') ==> ('DEROU', 'Z') ('RECH', 'Z')    
705                 ('TRANS', '4') ==> ('DEROU', 'Z') ('TACT', '11.0')    
1264                 ('TRANS', '4') ==> ('RECH', 'Z') ('TACT', '11.0')    
4306  ('TRANS', '4') ==> ('DEROU', 'Z') ('RECH', 'Z') ('TACT', '11.0')    

     right_length left_length  
                               
43              1           1  
128             1           1  
130             1           1  
698             2           1  
705             2           1  
1264            2           1  
4306            3           1

last one it the longest in the right side

In [124]:
df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,df.loc[:,('left','TRANS')]=='4'),df.left_length==1)].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]].tail(1)

sup conf  \
           sup conf   
4306  370098.0  1.0   

                                                                   rule  
                                                                   rule  
4306  ('TRANS', '4') ==> ('DEROU', 'Z') ('RECH', 'Z') ('TACT', '11.0')

so , the people who use the car for going to work are employed people either in real job or internship..

TYPMR attribute study the type of household of people 

In [140]:
df_rule3=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,df.loc[:,('left','TYPMR')]=='41.0'),df.left_length>1)].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule3.tail(1)

sup conf  \
            sup conf   
47576  367805.0  1.0   

                                                                                                                          rule  
                                                                                                                          rule  
47576  ('ANARR', 'Z') ('INAT', '11.0') ('TYPMR', '41.0') ==> ('DEROU', 'Z') ('IMMI', '2.0') ('NATC', '0.0') ('PNAI12', '1.0')

this shows that non immigrant families, but totally french ones are composed of a couple where only one man has the status of 'active with employment'

VOIT attribute

In [145]:
df_rule4=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,np.logical_not(df.loc[:,('left','VOIT')].isnull())),df.left_length>1)].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule4

sup conf  \
            sup conf   
179    438728.0  1.0   
182    411783.0  1.0   
307    438728.0  1.0   
310    411783.0  1.0   
424    438728.0  1.0   
...         ...  ...   
70844  389488.0  1.0   
70849  389488.0  1.0   
70851  389488.0  1.0   
70871  389488.0  1.0   
70874  389488.0  1.0   

                                                                                                                                         rule  
                                                                                                                                         rule  
179                                                                                        ('ANARR', 'Z') ('VOIT', '1.0') ==> ('DEROU', 'Z')   
182                                                                                        ('ANARR', 'Z') ('VOIT', '2.0') ==> ('DEROU', 'Z')   
307                                                                                       ('ANARR', 'Z') ('VOIT', '1.0') ==> ('IMMI', '2.0')   
310                                                                                       ('ANARR', 'Z') ('VOIT', '2.0') ==> ('IMMI', '2.0')   
424                                                                                     ('VOIT', '1.0') ('PNAI12', '1.0') ==> ('ANARR', 'Z')   
...                                                                                                                                       ...  
70844  ('ANARR', 'Z') ('DEROU', 'Z') ('INAT', '11.0') ('INFAM', '1.0') ('VOIT', '2.0') ==> ('IMMI', '2.0') ('NATC', '0.0') ('PNAI12', '1.0')   
70849  ('INFAM', '1.0') ('NATC', '0.0') ('VOIT', '2.0') ('PNAI12', '1.0') ==> ('ANARR', 'Z') ('DEROU', 'Z') ('IMMI', '2.0') ('INAT', '11.0')   
70851  ('INAT', '11.0') ('INFAM', '1.0') ('VOIT', '2.0') ('PNAI12', '1.0') ==> ('ANARR', 'Z') ('DEROU', 'Z') ('IMMI', '2.0') ('NATC', '0.0')   
70871  ('ANARR', 'Z') ('INFAM', '1.0') ('NATC', '0.0') ('VOIT', '2.0') ==> ('DEROU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('PNAI12', '1.0')   
70874  ('ANARR', 'Z') ('INAT', '11.0') ('INFAM', '1.0') ('VOIT', '2.0') ==> ('DEROU', 'Z') ('IMMI', '2.0') ('NATC', '0.0') ('PNAI12', '1.0')   

[771 rows x 3 columns]

as usuall all about french people, so french people have 2 cars per household

INFAM attribute

In [157]:
df_rule5=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,np.logical_not(df.loc[:,('left','INFAM')].isnull())),df.left_length>1)].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule5

sup conf  \
            sup conf   
164    844059.0  1.0   
292    844059.0  1.0   
380    844059.0  1.0   
381    844059.0  1.0   
455    569977.0  1.0   
...         ...  ...   
85998  484390.0  1.0   
86002  484390.0  1.0   
86003  484390.0  1.0   
86007  484390.0  1.0   
86008  484390.0  1.0   

                                                                                                                                                                      rule  
                                                                                                                                                                      rule  
164                                                                                                                    ('ANARR', 'Z') ('INFAM', '1.0') ==> ('DEROU', 'Z')   
292                                                                                                                   ('ANARR', 'Z') ('INFAM', '1.0') ==> ('IMMI', '2.0')   
380                                                                                                                 ('INFAM', '1.0') ('PNAI12', '1.0') ==> ('ANARR', 'Z')   
381                                                                                                                 ('ANARR', 'Z') ('INFAM', '1.0') ==> ('PNAI12', '1.0')   
455                                                                                                                    ('EMPL', 'ZZ') ('INFAM', '1.0') ==> ('DEROU', 'Z')   
...                                                                                                                                                                    ...  
85998  ('ANARR', 'Z') ('INAT', '11.0') ('INFAM', '1.0') ('TRANS', 'Z') ==> ('DEROU', 'Z') ('EMPL', 'ZZ') ('ILTUU', 'Z') ('IMMI', '2.0') ('NATC', '0.0') ('PNAI12', '1.0')   
86002  ('ANARR', 'Z') ('ILTUU', 'Z') ('INFAM', '1.0') ('NATC', '0.0') ==> ('DEROU', 'Z') ('EMPL', 'ZZ') ('IMMI', '2.0') ('INAT', '11.0') ('TRANS', 'Z') ('PNAI12', '1.0')   
86003  ('ANARR', 'Z') ('ILTUU', 'Z') ('INAT', '11.0') ('INFAM', '1.0') ==> ('DEROU', 'Z') ('EMPL', 'ZZ') ('IMMI', '2.0') ('NATC', '0.0') ('TRANS', 'Z') ('PNAI12', '1.0')   
86007  ('ANARR', 'Z') ('EMPL', 'ZZ') ('INFAM', '1.0') ('NATC', '0.0') ==> ('DEROU', 'Z') ('ILTUU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('TRANS', 'Z') ('PNAI12', '1.0')   
86008  ('ANARR', 'Z') ('EMPL', 'ZZ') ('INAT', '11.0') ('INFAM', '1.0') ==> ('DEROU', 'Z') ('ILTUU', 'Z') ('IMMI', '2.0') ('NATC', '0.0') ('TRANS', 'Z') ('PNAI12', '1.0')   

[8643 rows x 3 columns]

most household in GrandEst consist of one family and they are french

In [162]:
df_rule6=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,np.logical_not(df.loc[:,('left','VOIT')].isnull())),np.logical_not(df.loc[:,('left','GARL')].isnull()))].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule6

sup conf                                                 rule
          sup conf                                                 rule
520  367852.0  1.0  ('GARL', '1.0') ('VOIT', '2.0') ==> ('DEROU', 'Z')

In [168]:
df_rule7=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,np.logical_not(df.loc[:,('right','TACT')].isnull())),np.logical_not(df.loc[:,('left','ETUD')].isnull()))].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule7

sup conf  \
            sup conf   
841    368948.0  1.0   
3276   368948.0  1.0   
3278   368948.0  1.0   
4762   368948.0  1.0   
4765   368948.0  1.0   
12588  368948.0  1.0   
12591  368948.0  1.0   
12594  368948.0  1.0   
12597  368948.0  1.0   

                                                                                    rule  
                                                                                    rule  
841                                 ('EMPL', '16') ('ETUD', '2.0') ==> ('TACT', '11.0')   
3276                 ('DEROU', 'Z') ('EMPL', '16') ('ETUD', '2.0') ==> ('TACT', '11.0')   
3278                 ('EMPL', '16') ('ETUD', '2.0') ==> ('DEROU', 'Z') ('TACT', '11.0')   
4762                  ('EMPL', '16') ('ETUD', '2.0') ('RECH', 'Z') ==> ('TACT', '11.0')   
4765                  ('EMPL', '16') ('ETUD', '2.0') ==> ('RECH', 'Z') ('TACT', '11.0')   
12588  ('DEROU', 'Z') ('EMPL', '16') ('ETUD', '2.0') ('RECH', 'Z') ==> ('TACT', '11.0')   
12591  ('EMPL', '16') ('ETUD', '2.0') ('RECH', 'Z') ==> ('DEROU', 'Z') ('TACT', '11.0')   
12594  ('DEROU', 'Z') ('EMPL', '16') ('ETUD', '2.0') ==> ('RECH', 'Z') ('TACT', '11.0')   
12597  ('EMPL', '16') ('ETUD', '2.0') ==> ('DEROU', 'Z') ('RECH', 'Z') ('TACT', '11.0')

people who have Jobs with no time limit, permanent contract,or civil servant and are not registered in an educational institue 
are Employed people, including apprenticeship or paid internship.

In [179]:
df_rule8=df[np.logical_and(np.logical_and(df.loc[:,('conf','conf')]==1,np.logical_not(df.loc[:,('right','PNAI12')].isnull())),np.logical_not(df.loc[:,('left','TACT')].isnull()))].loc[:,[("sup","sup"),("conf","conf"),("rule","rule")]]
df_rule8

sup conf  \
            sup conf   
422    433896.0  1.0   
1790   433896.0  1.0   
1793   433896.0  1.0   
2199   415521.0  1.0   
2670   433896.0  1.0   
...         ...  ...   
82529  409018.0  1.0   
82544  409018.0  1.0   
82546  409018.0  1.0   
82608  409018.0  1.0   
82610  409018.0  1.0   

                                                                                                                                                       rule  
                                                                                                                                                       rule  
422                                                                                                  ('ANARR', 'Z') ('TACT', '11.0') ==> ('PNAI12', '1.0')   
1790                                                                                  ('ANARR', 'Z') ('DEROU', 'Z') ('TACT', '11.0') ==> ('PNAI12', '1.0')   
1793                                                                                  ('ANARR', 'Z') ('TACT', '11.0') ==> ('DEROU', 'Z') ('PNAI12', '1.0')   
2199                                                                                 ('ANARR', 'Z') ('ETUD', '2.0') ('TACT', '11.0') ==> ('PNAI12', '1.0')   
2670                                                                                 ('ANARR', 'Z') ('IMMI', '2.0') ('TACT', '11.0') ==> ('PNAI12', '1.0')   
...                                                                                                                                                     ...  
82529  ('ANARR', 'Z') ('ETUD', '2.0') ('IMMI', '2.0') ('INAT', '11.0') ('TACT', '11.0') ==> ('DEROU', 'Z') ('NATC', '0.0') ('RECH', 'Z') ('PNAI12', '1.0')   
82544  ('ANARR', 'Z') ('DEROU', 'Z') ('ETUD', '2.0') ('NATC', '0.0') ('TACT', '11.0') ==> ('IMMI', '2.0') ('INAT', '11.0') ('RECH', 'Z') ('PNAI12', '1.0')   
82546  ('ANARR', 'Z') ('DEROU', 'Z') ('ETUD', '2.0') ('INAT', '11.0') ('TACT', '11.0') ==> ('IMMI', '2.0') ('NATC', '0.0') ('RECH', 'Z') ('PNAI12', '1.0')   
82608  ('ANARR', 'Z') ('ETUD', '2.0') ('NATC', '0.0') ('TACT', '11.0') ==> ('DEROU', 'Z') ('IMMI', '2.0') ('INAT', '11.0') ('RECH', 'Z') ('PNAI12', '1.0')   
82610  ('ANARR', 'Z') ('ETUD', '2.0') ('INAT', '11.0') ('TACT', '11.0') ==> ('DEROU', 'Z') ('IMMI', '2.0') ('NATC', '0.0') ('RECH', 'Z') ('PNAI12', '1.0')   

[324 rows x 3 columns]